### ISSUE TITLE
Should I add Ping rate stochasticity to detection range model?

### ISSUE THREAD

**Issue by sebdalgarno** [Freshwater-Fish-Ecology-Laboratory/detrange#3]
based on joes comments in the meeting, should we calculate expected pings from time duration and min/max interval of tag?

Something like this:
```
## recalculate duration from Pings (used average interval of 120)
range_test$Duration_s <- range_test$Pings*120
## set min/max interval from tag info
range_test$Min_interval_s <- 60
range_test$Max_interval_s <- 180

## function to generate random transmission intervals and then calculate how many pings would occur in time duration
expected_pings <- function(duration, min, max){
  x <- as.integer(runif(duration, min, max))
  which.max(cumsum(x) >= duration)
}

## calculate new expected pings
range_test <- range_test %>%
  dplyr::rowwise() %>%
  dplyr::mutate(Pings2 = expected_pings(Duration_s, Min_interval_s, Max_interval_s))

```

It's interesting to see that Pings (calculated from average transmission interval) and Pings2 do differ quite a bit. Is this functionality you think people would want/expect?

<img width="830" alt="Screen Shot 2021-12-09 at 12 17 28 PM" src="https://user-images.githubusercontent.com/15878432/145469357-f52da3f2-5391-4878-b771-90ce6583ec42.png">

**Comment by sebdalgarno** [comment]
So the input data.frame expected from the user now includes:
Station, DateTimeIn, DateTimeOut, Min_transmission_interval_s, Max_transmission_interval_s

**Comment by sebdalgarno** [comment]
@eogmartins thoughts?

**Comment by eogmartins** [comment]
@sebdalgarno Seems like your Ping2 is just one realization of the uniform. If you repeat this several times, you will see that the numbers will vary across simulations. What you can do is run that simulation say 1000 times, pick the min and max number of transmissions in each case and then report the min and max detection efficiency based on both min and max transmissions.

**Comment by sebdalgarno** [comment]
that's a good idea. Although in this case I wonder how useful it is to run the simulation - why not just report detection efficiency for the min_interval (60 in this case) and max_interval (180) and perhaps the mean (120) as with enough simulations you would expect these to average out.

**Comment by eogmartins** [comment]
Both the min and max cases will generate estimates that are highly unlikely, as the the number of transmissions would be very unlikely to occur under those scenarios. I think the average number, assuming the user is considering a long duration in relation to the tag interval range, is a very good approximation.

**Comment by sebdalgarno** [comment]
Ok great that makes sense. So I think if I follow the train of thought, there is no need to introduce this element of stochasticity in calculating the pings? We can just calculate pings as duration/(mean(min_interval, max_interval)).
The question is then whether to stick with the original format of expected data input where we expect the user to provide Pings (expected detects) or whether we use the format above with DateTimeIn, DateTimeOut, Min_interval, Max_interval and calculate Pings for them

**Comment by eogmartins** [comment]
It may be easier to ask the user to provide the expected number. Not all transmitters are built with a min and max.
________________________________

**Comment by sebdalgarno** [comment]
OK yes sounds good. Well this was an interesting thought exercise anyway!

**Comment by eogmartins** [comment]
Indeed. Thanks.

From: Seb Dalgarno ***@***.***>
Date: Thursday, December 9, 2021 at 16:08
To: Freshwater-Fish-Ecology-Laboratory/detrange ***@***.***>
Cc: Eduardo Martins ***@***.***>, Mention ***@***.***>
Subject: Re: [Freshwater-Fish-Ecology-Laboratory/detrange] Should I add Ping rate stochasticity to detection range model? (Issue #3)
CAUTION: This email is not from UNBC. Avoid links and attachments. Don't buy gift cards.

OK yes sounds good. Well this was an interesting thought exercise anyway!
